# Generated by Django 4.0.2 on 2022-03-14 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0002_category_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='STORE.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Female', max_length=10),
        ),
    ]
