# Generated by Django 4.0.2 on 2022-03-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0003_product_category_alter_category_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
