# Generated by Django 4.0.2 on 2022-03-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0005_alter_category_gender_alter_category_metal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50, null=True)),
                ('phoneno', models.IntegerField(max_length=15)),
                ('emailadd', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
    ]
