# Generated by Django 4.0.2 on 2022-03-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0006_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50, null=True)),
                ('phone', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=500)),
                ('add1', models.CharField(max_length=100, null=True)),
                ('add2', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('zip', models.IntegerField(max_length=6, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
